// src/data.ts
export const data = [
    {
      year: 2020,
      totalJobs: 75,
      averageSalary: 102250.87,
      jobs: [
        { title: 'Azure Data Engineer', count: 1 },
        { title: 'Staff Data Analyst', count: 2 },
        { title: 'Staff Data Scientist', count: 1 },
        { title: 'Data Analyst', count: 6 },
        { title: 'Managing Director Data Science', count: 1 },
        { title: 'Sales Data Analyst', count: 1 },
        { title: 'Business Data Analyst', count: 1 },
        { title: 'Data Scientist', count: 21 },
        { title: 'Machine Learning Manager', count: 1 },
        { title: 'Data Engineer', count: 13 },
        { title: 'Product Data Analyst', count: 1 },
        { title: 'Big Data Engineer', count: 3 },
        { title: 'Research Scientist', count: 2 },
        { title: 'Data Science Consultant', count: 1 },
        { title: 'Machine Learning Engineer', count: 4 },
        { title: 'Machine Learning Infrastructure Engineer', count: 1 },
        { title: 'ML Engineer', count: 1 },
        { title: 'Lead Data Scientist', count: 2 },
        { title: 'Data Scientist', count: 2 },
        { title: 'Machine Learning Scientist', count: 1 },
        { title: 'Lead Data Engineer', count: 1 },
        { title: 'Lead Data Analyst', count: 1 },
        { title: 'BI Data Analyst', count: 1 },
        { title: 'Director of Data Science', count: 1 },
        { title: 'AI Scientist', count: 1 },
        { title: 'Computer Vision Engineer', count: 1 },
        { title: 'Principal Data Scientist', count: 1 },
        { title: 'Data Science Manager', count: 1 },
      ],
    },
    {
      year: 2021,
      totalJobs: 218,
      averageSalary: 99922.07,
      jobs: [
        { title: 'Staff Machine Learning Engineer', count: 1 },
        { title: 'Business Data Analyst', count: 2 },
        { title: 'Machine Learning Developer', count: 3 },
        { title: 'Data Science Lead', count: 1 },
        { title: 'AI Scientist', count: 3 },
        { title: 'Marketing Data Engineer', count: 1 },
        { title: 'Data Scientist', count: 40 },
        { title: 'Data Analyst', count: 20 },
        { title: 'Autonomous Vehicle Technician', count: 1 },
        { title: 'Data Engineer', count: 37 },
        { title: 'Machine Learning Research Engineer', count: 1 },
        { title: 'Computer Vision Software Engineer', count: 3 },
        { title: 'Cloud Data Architect', count: 1 },
        { title: 'Machine Learning Engineer', count: 18 },
        { title: 'Head of Data', count: 3 },
        { title: 'Research Scientist', count: 10 },
        { title: 'Data Science Manager', count: 6 },
        { title: 'Principal Data Scientist', count: 5 },
        { title: 'ML Engineer', count: 4 },
        { title: 'Computer Vision Engineer', count: 3 },
        { title: 'Applied Machine Learning Scientist', count: 2 },
        { title: 'Lead Data Scientist', count: 1 },
        { title: 'Machine Learning Scientist', count: 3 },
        { title: 'Applied Data Scientist', count: 2 },
        { title: 'Principal Data Engineer', count: 2 },
        { title: 'Big Data Engineer', count: 4 },
        { title: 'Data Architect', count: 3 },
        { title: 'BI Data Analyst', count: 4 },
        { title: 'Director of Data Science', count: 5 },
        { title: 'Data Science Consultant', count: 5 },
        { title: 'Head of Data Science', count: 2 },
        { title: 'Data Analytics Manager', count: 3 },
        { title: 'Data Science Engineer', count: 2 },
        { title: 'Data Analytics Engineer', count: 3 },
        { title: 'Lead Data Analyst', count: 2 },
        { title: 'Marketing Data Analyst', count: 1 },
        { title: 'Lead Data Engineer', count: 3 },
        { title: 'Cloud Data Engineer', count: 2 },
        { title: 'Principal Data Analyst', count: 1 },
        { title: 'Big Data Architect', count: 1 },
        { title: 'Staff Data Scientist', count: 1 },
        { title: 'Machine Learning Infrastructure Engineer', count: 1 },
        { title: 'Finance Data Analyst', count: 1 },
        { title: 'Data Specialist', count: 1 },
      ],
    },
    {
      year: 2022,
      totalJobs: 1655,
      averageSalary: 134349.50,
      jobs: [
        { title: 'AI Engineer', count: 1 },
        { title: 'AI Architect', count: 1 },
        { title: 'BI Analyst', count: 5 },
        { title: 'Admin & Data Analyst', count: 1 },
        { title: 'AI Research Engineer', count: 1 },
        { title: 'Machine Learning Scientist', count: 14 },
        { title: 'Applied Machine Learning Scientist', count: 9 },
        { title: 'Research Engineer', count: 8 },
        { title: 'Business Intelligence Developer', count: 1 },
        { title: 'Data Science Manager', count: 30 },
        { title: 'Data Scientist', count: 404 },
        { title: 'Machine Learning Engineer', count: 108 },
        { title: 'AI Developer', count: 1 },
        { title: 'Data Engineer', count: 488 },
        { title: 'Lead Data Scientist', count: 6 },
        { title: 'BI Developer', count: 3 },
        { title: 'Data Analyst', count: 272 },
        { title: 'Machine Learning Software Engineer', count: 5 },
        { title: 'Research Scientist', count: 15 },
        { title: 'Business Data Scientist', count: 7 },
        { title: 'Computer Vision Engineer', count: 3 },
        { title: 'Data Analytics Manager', count: 7 },
        { title: 'Manager Data Management', count: 1 },
        { title: 'Data Science Consultant', count: 10 },
        { title: 'Applied Data Scientist', count: 5 },
        { title: 'AI Programmer', count: 1 },
        { title: 'Machine Learning Developer', count: 5 },
        { title: 'ML Engineer', count: 15 },
        { title: 'Cloud Database Engineer', count: 2 },
        { title: 'Product Data Analyst', count: 2 },
        { title: 'Applied Scientist', count: 18 },
        { title: 'NLP Engineer', count: 2 },
        { title: 'AI Scientist', count: 8 },
        { title: 'Analytics Engineer', count: 56 },
        { title: 'BI Data Analyst', count: 6 },
        { title: 'MLOps Engineer', count: 2 },
        { title: 'Data Specialist', count: 11 },
        { title: 'Data Architect', count: 46},
        { title: 'Principal Machine Learning Engineer', count: 1 },
        { title: 'Machine Learning Researcher', count: 5 },
      { title: 'Data Analytics Consultant', count: 2 },
      { title: 'Machine Learning Research Engineer', count: 1 },
      { title: 'Deep Learning Engineer', count: 2 },
      { title: 'Data Management Specialist', count: 1 },
      { title: 'Data Science Tech Lead', count: 1 },
      { title: 'Data Scientist Lead', count: 2 },
      { title: 'Data Manager', count: 7 },
      { title: 'Head of Data', count: 4 },
      { title: 'Data Operations Analyst', count: 4 },
      { title: 'Data Operations Engineer', count: 8 },
      { title: 'Marketing Data Analyst', count: 1 },
      { title: 'Data Science Lead', count: 1 },
      { title: 'Big Data Engineer', count: 1 },
      { title: 'Principal Data Architect', count: 1 },
      { title: 'Machine Learning Manager', count: 2},
      { title: 'Lead Machine Learning Engineer', count: 3 },
      { title: 'Data Analytics Engineer', count: 2 },
      { title: 'ETL Developer', count: 10 },
      { title: 'Director of Data Science', count: 2 },
      { title: 'Financial Data Analyst', count: 2 },
      { title: 'Machine Learning Infrastructure Engineer', count: 3 },
      { title: 'Lead Data Engineer', count: 1},
      { title: 'Head of Machine Learning', count: 1 },
      { title: 'Data Science Engineer', count: 1 },
      { title: 'Head of Data Science', count: 2 },
      { title: 'Principal Data Analyst', count: 1 },
      { title: 'Data Analytics Lead', count: 1 },
      { title: 'Computer Vision Software Engineer', count: 1},
      { title: 'Principal Data Scientist', count: 1 },
    ],
    },
    {
      year: 2023,
      totalJobs: 8519,
      averageSalary: 153732.66,
      jobs: [
        { title: 'Data Analyst', count: 1266 },
        { title: 'Data DevOps Engineer', count: 3 },
        { title: 'Prompt Engineer', count: 5 },
        { title: 'Research Engineer', count: 164 },
        { title: 'Admin & Data Analyst', count: 1 },
        { title: 'Data Modeler', count: 28 },
        { title: 'Data Science Manager', count: 61 },
        { title: 'Research Analyst', count: 57 },
        { title: 'Data Engineer', count: 1852 },
        { title: 'ETL Developer', count: 10 },
        { title: 'Machine Learning Engineer', count: 966 },
        { title: 'Data Scientist', count: 1711 },
        { title: 'Data Specialist', count: 36 },
        { title: 'Data Strategist', count: 20 },
        { title: 'Business Intelligence Developer', count: 20 },
        { title: 'Business Intelligence Analyst', count: 78 },
        { title: 'Data Science Lead', count: 22 },
        { title: 'ML Engineer', count: 102 },
        { title: 'Analytics Engineer', count: 222 },
        { title: 'BI Developer', count: 55 },
        { title: 'Data Quality Manager', count: 2 },
        { title: 'Applied Scientist', count: 280 },
        { title: 'Head of Data', count: 28 },
        { title: 'Research Scientist', count: 286 },
        { title: 'Data Architect', count: 200 },
        { title: 'Data Science', count: 38 },
        { title: 'Business Intelligence Engineer', count: 164 },
        { title: 'Data Science Consultant', count: 35 },
        { title: 'Machine Learning Scientist', count: 64 },
        { title: 'Data Product Manager', count: 14 },
        { title: 'Business Intelligence Manager', count: 6 },
        { title: 'Data Manager', count: 135 },
        { title: 'Data Analytics Manager', count: 31 },
        { title: 'Computer Vision Engineer', count: 21 },
        { title: 'AI Product Manager', count: 1 },
        { title: 'Data Analytics Lead', count: 5 },
        { title: 'Director of Data Science', count: 23 },
        { title: 'Data Product Owner', count: 4 },
        { title: 'Data Developer', count: 10 },
        { title: 'Machine Learning Infrastructure Engineer', count: 26 },
        { title: 'Data Lead', count: 16 },
        { title: 'Data Integration Engineer', count: 4 },
        { title: 'Data Management Analyst', count: 4 },
        { title: 'Data Visualization Specialist', count: 10 },
        { title: 'BI Analyst', count: 27 },
        { title: 'Data Science Engineer', count: 13 },
        { title: 'Business Data Analyst', count: 9 },
        { title: 'Machine Learning Operations Engineer', count: 3 },
        { title: 'Data Analyst Lead', count: 1 },
        { title: 'NLP Engineer', count: 13 },
        { title: 'MLOps Engineer', count: 11 },
        { title: 'Marketing Data Scientist', count: 1 },
        { title: 'AI Scientist', count: 10 },
        { title: 'Insight Analyst', count: 10 },
        { title: 'Machine Learning Researcher', count: 12 },
        { title: 'Data Quality Analyst', count: 20 },
        { title: 'Deep Learning Engineer', count: 10 },
        { title: 'AI Developer', count: 17 },
        { title: 'Data Science Director', count: 4 },
        { title: 'Machine Learning Modeler', count: 2 },
        { title: 'BI Data Analyst', count: 6 },
        { title: 'Data Integration Specialist', count: 11 },
        { title: 'Data Science Practitioner', count: 10 },
        { title: 'Data Management Specialist', count: 4 },
        { title: 'AI Architect', count: 12 },
        { title: 'Business Intelligence Specialist', count: 4 },
        { title: 'Data Quality Engineer', count: 3 },
        { title: 'AI Programmer', count: 5 },
        { title: 'Decision Scientist', count: 38 },
        { title: 'Financial Data Analyst', count: 2 },
        { title: 'Data Strategy Manager', count: 4 },
        { title: 'Data Visualization Engineer', count: 4 },
        { title: 'Principal Data Scientist', count: 3 },
        { title: 'Data Infrastructure Engineer', count: 12 },
        { title: 'Machine Learning Software Engineer', count: 10 },
        { title: 'AI Research Engineer', count: 4 },
        { title: 'Head of Machine Learning', count: 2 },
        { title: 'Applied Data Scientist', count: 5 },
        { title: 'Data Operations Analyst', count: 6 },
        { title: 'Data Operations Engineer', count: 8 },
        { title: 'Machine Learning Manager', count: 1 },
        { title: 'Lead Data Scientist', count: 1 },
        { title: 'Principal Machine Learning Engineer', count: 2 },
        { title: 'Principal Data Engineer', count: 1 },
        { title: 'Power BI Developer', count: 1 },
        { title: 'Head of Data Science', count: 8 },
        { title: 'Consultant Data Engineer', count: 1 },
        { title: 'Machine Learning Specialist', count: 2 },
        { title: 'Business Intelligence Data Analyst', count: 2 },
        { title: 'Data Operations Manager', count: 2 },
        { title: 'Lead Machine Learning Engineer', count: 1 },
        { title: 'Data Modeller', count: 2 },
        { title: 'Finance Data Analyst', count: 2 },
        { title: 'Software Data Engineer', count: 3 },
        { title: 'Machine Learning Research Engineer', count: 2 },
        { title: 'Compliance Data Analyst', count: 2 },
        { title: 'Data Operations Specialist', count: 4 },
        { title: 'Cloud Data Engineer', count: 2 },
        { title: 'Analytics Engineering Manager', count: 1 },
        { title: 'Staff Data Analyst', count: 1 },
        { title: 'Applied Machine Learning Scientist', count: 3 },
        { title: 'AWS Data Architect', count: 1 },
        { title: 'Product Data Analyst', count: 3 },
        { title: 'Data Visualization Analyst', count: 2 },
        { title: 'Autonomous Vehicle Technician', count: 1 },
        { title: 'Applied Machine Learning Engineer', count: 3 },
        { title: 'ETL Engineer', count: 2 },
        { title: 'Big Data Engineer', count: 2 },
        { title: 'Lead Data Analyst', count: 2 },
        { title: 'BI Data Engineer', count: 1 },
        { title: 'Cloud Database Engineer', count: 3 },
        { title: 'Deep Learning Researcher', count: 1 },
        { title: 'Data Analytics Specialist', count: 2 },
        { title: 'Big Data Architect', count: 1 },
        { title: 'Computer Vision Software Engineer', count: 1 },
        { title: 'Azure Data Engineer', count: 1 },
      ],
    },
    {
      year: 2024,
      totalJobs: 6027,
      averageSalary: 150643.25,
      jobs: [
        { title: 'Data Scientist', count: 1136 },
        { title: 'Data Science Manager', count: 24 },
        { title: 'Business Intelligence Engineer', count: 84 },
        { title: 'Data Architect', count: 184 },
        { title: 'Data Analyst', count: 864 },
        { title: 'Business Intelligence', count: 98 },
        { title: 'ML Engineer', count: 76 },
        { title: 'Data Modeler', count: 28 },
        { title: 'Machine Learning Engineer', count: 607 },
        { title: 'Data Integration Specialist', count: 12 },
        { title: 'Research Scientist', count: 216 },
        { title: 'Data Engineer', count: 1066 },
        { title: 'Data Product Manager', count: 22 },
        { title: 'Data Manager', count: 68 },
        { title: 'Data Visualization Specialist', count: 4 },
        { title: 'Data Science', count: 233 },
        { title: 'Data Specialist', count: 38 },
        { title: 'Business Intelligence Lead', count: 10 },
        { title: 'Research Analyst', count: 66 },
        { title: 'Business Intelligence Analyst', count: 113 },
        { title: 'AI Engineer', count: 70 },
        { title: 'AI Software Engineer', count: 5 },
        { title: 'Machine Learning Scientist', count: 56 },
        { title: 'Data Science Engineer', count: 13 },
        { title: 'Applied Scientist', count: 135 },
        { title: 'Machine Learning Operations Engineer', count: 6 },
        { title: 'Analytics Engineer', count: 153 },
        { title: 'Data Management Analyst', count: 18 },
        { title: 'Encounter Data Management Professional', count: 8 },
        { title: 'Data Analytics Specialist', count: 6 },
        { title: 'Head of Data', count: 26 },
        { title: 'Data Analytics Lead', count: 17 },
        { title: 'Research Engineer', count: 134 },
        { title: 'AI Scientist', count: 4 },
        { title: 'Business Intelligence Developer', count: 36 },
        { title: 'Machine Learning Developer', count: 2 },
        { title: 'Data Management Specialist', count: 6 },
        { title: 'Data Infrastructure Engineer', count: 10 },
        { title: 'BI Developer', count: 10 },
        { title: 'Admin & Data Analyst', count: 2 },
        { title: 'Insight Analyst', count: 4 },
        { title: 'Consultant Data Engineer', count: 1 },
        { title: 'Business Intelligence Manager', count: 14 },
        { title: 'Manager Data Management', count: 1 },
        { title: 'Data Quality Manager', count: 4 },
        { title: 'Data Analytics Manager', count: 21 },
        { title: 'Robotics Engineer', count: 12 },
        { title: 'Business Intelligence Specialist', count: 2 },
        { title: 'Data Operations Analyst', count: 14 },
        { title: 'Director of Business Intelligence', count: 2 },
        { title: 'Data Product Owner', count: 4 },
        { title: 'Data Operations Manager', count: 2 },
        { title: 'AI Research Scientist', count: 3 },
        { title: 'Data Operations Specialist', count: 8 },
        { title: 'Bear Robotics', count: 2 },
        { title: 'Data Science Consultant', count: 32 },
        { title: 'Data Lead', count: 10 },
        { title: 'Data Operations Associate', count: 6 },
        { title: 'Lead Data Scientist', count: 1 },
        { title: 'MLOps Engineer', count: 10 },
        { title: 'Applied Research Scientist', count: 1 },
        { title: 'Prompt Engineer', count: 12 },
        { title: 'BI Analyst', count: 12 },
        { title: 'Data Integration Engineer', count: 16 },
        { title: 'Machine Learning Infrastructure Engineer', count: 2 },
        { title: 'Data Developer', count: 20 },
        { title: 'CRM Data Analyst', count: 1 },
        { title: 'ETL Developer', count: 8 },
        { title: 'AI Architect', count: 16 },
        { title: 'Cloud Database Engineer', count: 8 },
        { title: 'Data Science Analyst', count: 4 },
        { title: 'Data Science Practitioner', count: 6 },
        { title: 'BI Data Analyst', count: 2 },
        { title: 'Applied Data Scientist', count: 1 },
        { title: 'Data Quality Engineer', count: 2 },
        { title: 'Computational Biologist', count: 4 },
        { title: 'Big Data Engineer', count: 2 },
        { title: 'Data Analytics Associate', count: 1 },
        { title: 'Data Reporting Analyst', count: 2 },
        { title: 'Data Management Consultant', count: 2 },
        { title: 'Data Quality Analyst', count: 4 },
        { title: 'Robotics Software Engineer', count: 8 },
        { title: 'Machine Learning Researcher', count: 4 },
        { title: 'Data Science Director', count: 4 },
        { title: 'Data Strategist', count: 4 },
        { title: 'Big Data Developer', count: 1 },
        { title: 'Quantitative Research Analyst', count: 1 },
        { title: 'Lead Machine Learning Engineer', count: 1 },
        { title: 'Machine Learning Research Engineer', count: 1 },
        { title: 'Data Analytics Consultant', count: 6 },
        { title: 'AI Research Engineer', count: 2 },
        { title: 'AI Programmer', count: 1 },
        { title: 'ETL Engineer', count: 1 },
        { title: 'AI Product Manager', count: 2 },
        { title: 'AI Developer', count: 1 },
        { title: 'Computer Vision Engineer', count: 4 },
        { title: 'Head of Machine Learning', count: 4 },
        { title: 'Data Analyst Lead', count: 1 },
        { title: 'Data Integration Developer', count: 4 },
        { title: 'ML Ops Engineer', count: 2 },
        { title: 'Data Pipeline Engineer', count: 2 },
        { title: 'Lead Data Analyst', count: 1 },
        { title: 'Data Science Lead', count: 2 },
        { title: 'Director of Data Science', count: 2 },
        { title: 'Managing Director Data Science', count: 1 },
      ],
    },
  ];